fix(TECH): ecr scan results fix
hey-car/action-ecr-scan pull request #2
Opened 2024-03-21 16:48 UTC by stevenquanheycar

PR to fix missing git cli on docker image

2024-03-21 16:50 UTC, amohamedhey approved these changes

2024-03-22 08:38 UTC, amohamedhey requested changes
need to add gitHub-cli

2024-03-22 08:38 UTC, amohamedhey commented on Dockerfile
> +ARG GIT_VERSION="2"
```suggestion
ARG GIT_VERSION="2"
ARG GITHUB_CLI_VERSION="2"
```

2024-03-22 08:38 UTC, amohamedhey commented on Dockerfile
> +    apk add --no-cache bash~=${BASH_VERSION} aws-cli~=${AWS_CLI_VERSION} jq~=${JQ_VERSION} curl~=${CURL_VERSION} git~=${GIT_VERSION}; \
```suggestion
    apk add --no-cache bash~=${BASH_VERSION} aws-cli~=${AWS_CLI_VERSION} jq~=${JQ_VERSION} curl~=${CURL_VERSION} git~=${GIT_VERSION} github-cli~=${GITHUB_CLI_VERSION}; \
```

2024-03-22 09:48 UTC, amohamedhey approved these changes

2024-03-22 09:48 UTC, piximos approved these changes

2024-03-22 09:48 UTC, merged